# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0c757cec53e797986a565e40b7b9996e720643323cbf4c97e8a5434fc184a662c664fbb5f9c9d2ea0288f859878ae2a64d80d68e49d14bac6077a34ee9e9edbc

test:
  secret_key_base: 9568e4d5057ba5d5419c740a119513c2a059069e789dd1d5b034a9232a3f54adb4ffb8ee980e503eed3938b01e1c1ac08ff7989d746d8409112210f3978eb1d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
